apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubernetes-auth0-concept-authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kubernetes-auth0-concept-authentication
  template:
    metadata:
      labels:
        app: kubernetes-auth0-concept-authentication 
    spec:
      containers:
        - name: kubernetes-auth0-concept-authentication 
          image: brandonkorouscontainers.azurecr.io/kubernetes-auth0-concept-authentication 
          ports:
          - containerPort: 80
          env:
            "Auth0_Authority": "$(Auth0:Authority)"
            "ASPNETCORE_ENVIRONMENT": "Development2"
            "Auth0_ClientId": "$(Auth0:ClientId)"
            "Auth0_ClientSecret": "$(Auth0:ClientSecret)"