apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubernetes-auth0-concept-authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kubernetes-auth0-concept-authentication
  template:
    metadata:
      labels:
        app: kubernetes-auth0-concept-authentication 
    spec:
      containers:
        - name: kubernetes-auth0-concept-authentication 
          image: brandonkorouscontainers.azurecr.io/kubernetes-auth0-concept-authentication 
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "Auth0_Authority"
            valueFrom:
              secretKeyRef: 
                name: auth0-images-secrets
                key: Auth0_Authority
          - name: "Auth0_ClientId"
            valueFrom:
              secretKeyRef: 
                name: auth0-images-secrets
                key: Auth0_ClientId
          - name: "Auth0_ClientSecret"
            valueFrom:
              secretKeyRef: 
                name: auth0-images-secrets
                key: Auth0_ClientSecret