apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  #name: letsencrypt-staging
  name: letsencrypt-kubernetes-auth0-concept-authentication
  namespace: cert-manager
spec:
  acme:
    email: me@brandonkorous.com
    privateKeySecretRef:
      name: wize-ingress-kubernetes-auth0-concept-authentication-certificate
      #name: letsencrypt-staging
      #name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress: 
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wize-ingress-development-clients-kubernetes-auth0-concept-authentication
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-kubernetes-auth0-concept-authentication
    #ingress.kubernetes.io/ssl-redirect: "true"
    #kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - kubernetes-auth0-concept-authentication.samples.brandonkorous.com
    secretName: wize-ingress-kubernetes-auth0-concept-authentication-certificate
  rules:
  - host: kubernetes-auth0-concept-authentication.samples.brandonkorous.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: kubernetes-auth0-concept-authentication-service
             port: 
               number: 443